# Generated by Django 4.0.3 on 2022-03-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
                ('year', models.IntegerField()),
            ],
            options={
                'db_table': 'Movie',
            },
        ),
    ]
