# Generated by Django 4.0.3 on 2022-03-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyPlatforms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platforms_name', models.CharField(max_length=255)),
                ('model_lunch', models.DateField()),
                ('model_number', models.IntegerField()),
                ('model_price', models.IntegerField()),
            ],
            options={
                'db_table': 'BuyPlatforms',
            },
        ),
        migrations.CreateModel(
            name='Phonelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('model_number', models.IntegerField()),
                ('model_year', models.IntegerField()),
                ('model_detail', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Phonelist',
            },
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
